http-server:
  address: "localhost:8080"
  timeout: 10s
  idle_timeout: 30s

jwt:
  access_ttl: 10m
  refresh_ttl: 168h

cors:
  allowed_origins: 
    - "*"
  allowed_methods: 
    - "*"
  allowed_headers:
    - "*"
  allow_credentials: true