---
cors:
  allow_credentials: true
  allowed_headers:
    - Authorization
    - Content-Type
    - Accept
  allowed_methods:
    - GET
    - DELETE
    - POST
  allowed_origins:
    - apigateawaydomain
http-server:
  address: 0.0.0.0:10000
  idle_timeout: 30s
  timeout: 10s
jwt:
  access_ttl: 10m
  refresh_ttl: 168h